num1=float(input("Enter first number"))
num2=float(input("Enter second number"))
print(f"The sum of {num1} and {num2} is {num1+num2}")
print(f"The difference of {num1} and {num2} is {num1-num2}")
print(f"The remainder of {num1} and {num2} is {num1%num2}")
print(f"The product of {num1} and {num2} is {num1**num2}")
print(f"The quotient of {num1} and {num2} is {num1/num2}")